import { z } from "zod";

/**
 * WorkspaceConfigSchema — the whole tenant customization surface, one object
 * (plan `docs/plans/2026-07-11-adapt-it-saas-plan.md` § "The workspace config
 * shape"). Every field is generated by the AI onboarding (P3) and editable in
 * the Customization Studio (P4); this is the validated contract both write
 * through, and the shape `src/workspace/store.ts` enforces on every DB write.
 *
 * Every field is REQUIRED (no `.optional()` anywhere) — a workspace is either
 * fully configured or it doesn't validate; only `proof` and `sampleFeed` may
 * be empty ARRAYS (a brand-new workspace may have no proof point yet, and the
 * default EliseAI workspace uses the real `practices` table instead of a
 * generated sample feed — see `src/workspace/default.ts`).
 */

/** `#rrggbb` — case-insensitive, always 6 hex digits (no `#fff` shorthand, no alpha). */
const hexColor = z
  .string()
  .regex(/^#[0-9a-f]{6}$/i, "must be a #rrggbb hex color");

const brandSchema = z.object({
  /** The tenant's own product name, replaces "Moment" everywhere post-onboarding. */
  productName: z.string().min(1).max(80),
  companyName: z.string().min(1).max(80),
  primaryColor: hexColor,
  accentColor: hexColor,
  /** Hero gradient start/end — see `gradients.healthHero` for the default's provenance. */
  heroFrom: hexColor,
  heroTo: hexColor,
  /** Wordmark text shown in TopNav until a tenant uploads a logo. */
  logoText: z.string().min(1).max(40),
  fontChoice: z.string().min(1).max(60),
});

const businessSchema = z.object({
  oneLiner: z.string().min(1).max(200),
  whatYouSell: z.string().min(1).max(2000),
  icp: z.string().min(1).max(500),
  decisionMakerRoles: z.array(z.string().min(1).max(80)).min(1).max(20),
  geography: z.string().min(1).max(200),
});

const signalSchema = z.object({
  name: z.string().min(1).max(120),
  /** Free-form (plan OUT-of-scope: not constrained to the healthcare `signal_kind` enum). */
  kind: z.string().min(1).max(60),
  /** Why this signal predicts a buy — the Adapter's reasoning, shown to the user. */
  why: z.string().min(1).max(500),
  dataSource: z.string().min(1).max(200),
  freshnessDays: z.number().int().positive().max(730),
});

const objectionSchema = z.object({
  q: z.string().min(1).max(300),
  rebuttal: z.string().min(1).max(1000),
});

const openerSchema = z.object({
  leadWith: z.string().min(1).max(500),
  vocabulary: z.array(z.string().min(1).max(60)).min(1).max(20),
  tone: z.string().min(1).max(200),
  exampleOpener: z.string().min(1).max(1000),
});

const pitchSchema = z.object({
  painFit: z.string().min(1).max(1000),
  opener: openerSchema,
  discoveryQuestions: z.array(z.string().min(1).max(300)).min(1).max(10),
  objections: z.array(objectionSchema).min(1).max(10),
});

/**
 * A real, citable proof point, or the honest `pending` state (mirrors
 * `src/packs/schema.ts`'s `proof_pending` sentinel — R5: a proof point is
 * never silently blank). Kept as an untagged union (not `discriminatedUnion`)
 * because the two shapes share no common literal key by design (plan spec).
 */
const provenProofSchema = z.object({
  claim: z.string().min(1).max(300),
  metric: z.string().min(1).max(200),
  sourceUrl: z.url(),
});

const pendingProofSchema = z.object({
  claim: z.string().min(1).max(300),
  tag: z.literal("pending"),
});

const proofPointSchema = z.union([provenProofSchema, pendingProofSchema]);

const sampleSignalSchema = z.object({
  name: z.string().min(1).max(120),
  kind: z.string().min(1).max(60),
});

const whoToContactSchema = z.object({
  name: z.string().min(1).max(120),
  role: z.string().min(1).max(120),
  channel: z.string().min(1).max(60),
  personalization: z.string().min(1).max(500),
});

const sampleBriefSchema = z.object({
  whoToContact: whoToContactSchema,
  recommendedAction: z.string().min(1).max(300),
  painFit: z.string().min(1).max(1000),
  proofLine: z.string().min(1).max(300),
  discoveryQuestions: z.array(z.string().min(1).max(300)).min(1).max(10),
  objections: z.array(objectionSchema).min(1).max(10),
});

const sampleProspectSchema = z.object({
  id: z.string().min(1).max(80),
  name: z.string().min(1).max(120),
  oneLine: z.string().min(1).max(300),
  headline: z.string().min(1).max(200),
  freshnessLabel: z.string().min(1).max(60),
  signals: z.array(sampleSignalSchema).min(1).max(10),
  brief: sampleBriefSchema,
});

export const WorkspaceConfigSchema = z.object({
  brand: brandSchema,
  business: businessSchema,
  signals: z.array(signalSchema).min(1).max(20),
  pitch: pitchSchema,
  /** May be empty — a workspace with no proof point yet is honest, not broken. */
  proof: z.array(proofPointSchema).max(20),
  /** May be empty — the default EliseAI workspace reads `practices` instead. */
  sampleFeed: z.array(sampleProspectSchema).max(20),
});

export type WorkspaceConfig = z.infer<typeof WorkspaceConfigSchema>;
